version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/deploy/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: stopApp.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: startApp.sh
      timeout: 300
      runas: ec2-user

#  ValidateService:
#    - location: healthCheck.sh
#      timeout: 60
#      runas: ec2-user
