version: 0.2

phases:
  install:
    runtime-versions:
        java: openjdk8     
  build:
    commands:
      - echo Build completed on `date`
      - mvn package -DskipTests
  post_build:
    commands:
      - chmod +x scripts/**
      - chmod +x ./target/*.jar

artifacts:
  files:
    - target/test-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/**
  discard-paths: yes
